name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies for client
        working-directory: ./client
        run: npm i
      - name: Install dependencies for server
        working-directory: ./server
        run: npm i
      - run: sudo pm2 restart client
      - run: sudo pm2 restart server
      - run: sudo pm2 save
      - run: sudo service nginx restart
